// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "OnePen",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "OnePen",
            targets: ["AppModule"],
            bundleIdentifier: "com.settasit.onepen",
            teamIdentifier: "859P739SU5",
            displayVersion: "1.1.2",
            bundleVersion: "10",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.yellow),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight(.when(deviceFamilies: [.pad])),
                .landscapeLeft(.when(deviceFamilies: [.pad])),
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "Your camera is used to display virtual objects in augmented reality (AR)."),
                .photoLibraryAdd(purposeString: "Your photo library is used to add captured screenshots to your photos without accessing other images.")
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ],
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)
